"""Extract every number from the draft, in order, for the before/after diff.

    python3 -B extract_numbers.py --out numbers_before.txt
    ...   editing happens   ...
    python3 -B extract_numbers.py --out numbers_after.txt
    diff numbers_before.txt numbers_after.txt      # must be empty

This is a SAFETY CHECK, not a style detector. Its only job is to prove that a
language pass moved no number. It is deliberately over-inclusive: it would
rather flag a rewording that touches a digit than miss one.

WHAT COUNTS AS A NUMBER. Integers, decimals, signed values, percentages,
currency, p-values in scientific notation, and n/N pairs. Each is recorded with
the file, a running index, and about forty characters of surrounding text so a
diff points at the sentence rather than at a bare digit.

WHAT IS SKIPPED. Section and table cross-references (`T4`, `F2`, `§3`), because
renumbering a table is not a numeric claim, and markdown table pipes, because
the tables are generated by `tables/make_tables.py` and checked by
`tables/check_numbers.py` rather than by this script.

By default it reads the draft files named in DRAFT_GLOBS. Pass paths explicitly
to run it over anything else, which is how it was tested against the benchmark
paper before the draft existed.
"""

import argparse
import glob
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# The prose of the paper. Scaffolding documents are excluded: STRUCTURE.md,
# OUTLINE.md, LANGUAGE.md, STYLE.md and this log describe the paper rather
# than asserting its findings, so a number changing in them is not a defect.
DRAFT_GLOBS = ["draft/*.md", "draft/*.tex", "sections/*.md", "sections/*.tex"]

NUM = re.compile(r"""
    (?<![\w.])                 # not mid-identifier
    (?:
        \$\s?\d[\d,]*(?:\.\d+)?          # $12.51, $ 55.21
      | [+\u2212-]?\d[\d,]*\.\d+(?:e[+-]?\d+)?   # 0.6128, -3.4, 2.75e-24
      | [+\u2212-]?\d[\d,]*(?:e[+-]?\d+)?        # 115, 1,218
    )
    \s?%?                                        # trailing percent
""", re.X | re.I)

# Cross-references, not claims: T4, T4B, F2, section 3, figure 5, table 4,
# experiment 2, §5. "Experiment 2" names a section of this paper in the same way
# "Section 2" does, so it is skipped for the same reason: renumbering a pointer
# is not a change to a measured quantity. Every one of these forms was checked
# against the draft before being added, and none of them ever introduces a digit
# that is also a datum.
REF = re.compile(r"(?:\b[TF]\d+[A-Z]?\b|§\s?\d+|\bsection\s+\d+\b|\bfigure\s+\d+\b"
                 r"|\btable\s+\d+\b|\bexperiments?\s+\d+\b)", re.I)


def strip_noise(text, path):
    """Remove what is not prose: code fences, markdown tables, LaTeX tabulars."""
    text = re.sub(r"```.*?```", " ", text, flags=re.S)
    text = re.sub(r"\\begin\{(tabular|table)\}.*?\\end\{\1\}", " ", text, flags=re.S)
    if path.endswith(".md"):
        text = "\n".join(ln for ln in text.split("\n")
                         if not ln.lstrip().startswith("|"))
    return text


def canon(tok):
    """The comparable form of a captured token.

    Strips trailing punctuation the regex swallowed from the sentence, and
    normalises thousands separators and whitespace inside currency. `2,` and
    `2` are the same number; `1,218` and `1218` are the same number. Without
    this the check fires when a comma moves, which is a rewording rather than
    a defect, and a check that fires on every rewording certifies nothing.
    """
    t = tok.strip().rstrip(".,;:)")
    t = t.replace("$ ", "$").replace("−", "-")
    if re.fullmatch(r"\$?[+-]?[\d,]+(\.\d+)?%?", t):
        t = t.replace(",", "")
    return t


def numbers_in(path):
    raw = open(path, encoding="utf-8").read()
    text = strip_noise(raw, path)
    out = []
    for m in NUM.finditer(text):
        s, e = m.span()
        # skip if the match sits inside a cross-reference
        window = text[max(0, s - 12):e + 4]
        if any(r.start() <= 12 < r.end() for r in REF.finditer(window)):
            continue
        left = re.sub(r"\s+", " ", text[max(0, s - 42):s]).strip()
        right = re.sub(r"\s+", " ", text[e:e + 24]).strip()
        out.append((canon(m.group(0)), left, right))
    return out


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("paths", nargs="*", help="files to scan (default: the draft)")
    ap.add_argument("--out", default=None)
    ap.add_argument("--values", action="store_true",
                    help="emit normalised values only, one per line. THIS is "
                         "the canonical form for the before/after diff, because "
                         "the context around a number changes whenever a "
                         "sentence is reworded, which a language pass does on "
                         "purpose.")
    args = ap.parse_args(argv)

    paths = args.paths
    if not paths:
        for g in DRAFT_GLOBS:
            paths += sorted(glob.glob(os.path.join(HERE, g)))
    paths = [p for p in paths if os.path.isfile(p)]

    lines = []
    total = 0
    if not paths:
        lines.append("NO DRAFT FILES FOUND")
        lines.append("")
        lines.append("Searched, relative to " + HERE + ":")
        for g in DRAFT_GLOBS:
            lines.append("  " + g)
        lines.append("")
        lines.append("The paper has no prose yet, so there are no numbers to "
                     "protect. Re-run this once a draft exists, before the "
                     "first edit.")
    for p in paths:
        rel = os.path.relpath(p, HERE)
        nums = numbers_in(p)
        if args.values:
            for val, _, _ in nums:
                lines.append(rel + "\t" + val)
        else:
            lines.append("### " + rel + "  (" + str(len(nums)) + " numbers)")
            for i, (val, left, right) in enumerate(nums, 1):
                lines.append("{:04d}  {:>14s}  ...{} [[{}]] {}...".format(
                    i, val, left[-42:], val, right[:24]))
            lines.append("")
        total += len(nums)
    # The summary is printed, never written into the values file, because the
    # values file is diffed byte for byte and a count line would make a
    # change in the number of numbers look like a change in a number.
    if not args.values:
        lines.append("TOTAL " + str(total) + " numbers across " + str(len(paths))
                     + " file(s)")

    text = "\n".join(lines) + "\n"
    if args.out:
        dest = args.out if os.path.isabs(args.out) else os.path.join(HERE, args.out)
        with open(dest, "w", encoding="utf-8") as f:
            f.write(text)
        print("wrote " + dest)
        print("TOTAL " + str(total) + " numbers across " + str(len(paths)) + " file(s)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
